### ISSUE TITLE
Custom Gene Signature Issue

### ISSUE THREAD

**Issue by gabelim** [ebecht/MCPcounter#10]
Hi @ebecht,

I have a similar issue as previously reported.
In my case I have a custom gene signature I'd like to use (I've exported out as comb1.txt)
I'd made a gene expression dataframe that I've exported out as DFL1.txt.

I had the following warning (seems like the code is still looking for MCPcounter default signature:

`> MCP=MCPcounter.estimate(DFL1, featuresType="HUGO_symbols", genes = comb1)
Warning message:
In MCPcounter.estimate(DFL1, featuresType = "HUGO_symbols", genes = comb1) :
  Found no markers for population(s): T cells, Cytotoxic lymphocytes, B lineage, Monocytic lineage, Myeloid dendritic cells, Endothelial cells, Fibroblasts`

I also ran the following check as you had previously listed:
`> intersect(rownames(DFL1),genes[ ,"HUGO symbols"])
Error in genes[, "HUGO symbols"] : 
  object of type 'closure' is not subsettable`

`> intersect(rownames(DFL1),comb1[ ,"HUGO symbols"])
 [1] "CD6"      "TNFRSF17" "FOXP3"    "CD84"     "ITM2A"    "LAG3"     "TCL1A"    "IL21R"   
 [9] "NKG7"     "RCAN3"    "FCRL2"    "BLK"      "AMIGO2"   "IGFBP4"   "GZMA"     "CD8A"    
[17] "MS4A1"    "CD3G"     "EOMES"    "TRAT1"    "ICOS"     "CD3D"     "PNOC"     "PTGER4"  
[25] "CD19"     "CD163"    "PRF1"     "SH2D1A"   "CD3E"     "SPIB"    `

Attached are my files. Appreciate if you can help to see if its a formatting issue, or something... I'm quite new to R, so apologies in advance!

[comb1.txt](https://github.com/ebecht/MCPcounter/files/3383723/comb1.txt)
[DFL1.txt](https://github.com/ebecht/MCPcounter/files/3383724/DFL1.txt)

Much Thanks

**Comment by ebecht** [comment]
Hi @gabelim 

I'm happy to help but please give the following some consideration:

I'd like to advise against using these custom gene signatures. One of the main aspect of our work (probably not highlighted well enough) was to not oversell our tool by proposing signatures for cell types for which we were not confident transcriptomic markers would be available. In your case it appears that you are including markers that are likely not specific. I would prefer to not see these signatures being associated with core MCPcounter gene sets that were carefully selected.
If you want to use them anyway, make sure that they are presented as clearly distinct from what our tool outputs.

In any case, your issue appears to be that the first column of `comb1` are numbers instead of the expected gene names. You need to delete that column.

I hope you will understand,

Best
Etienne

**Comment by gabelim** [comment]
Hi Etienne,

Got you. Thanks for your reply and will heed your advice. 

Best
Gab
