### ISSUE TITLE
Yet another custom signature

### ISSUE THREAD

**Issue by Exenter** [ebecht/MCPcounter#12]
Hi @ebecht 

Sorry to open another issue for custom signature, I obviously read your post in #5 and #10 before asking. I do took note of what was said here.

That being said, I get the same error as #10, "Found no markers for population". 
Also ran this line `intersect(rownames(Lp_FFPE_numeric),df[ ,"HUGO symbols"])` and got 300+ results so it's ok here.
Here's the head of the signature I am trying to use :
```
"HUGO symbols"	"Cell population"	"ENTREZID"
"NIPAL3"	"CD4"	" "
"TMEM176A"	"Mono"	" "
"MCUB"	"CD4"	" "
"MATK"	"M2"	" "
"CD79B"	"B"	" "
```
I also tried putting it after the provided genes.txt but then it only outputs scores for the original genes.

(also got an error with curl because the link isn't https but this doesn't really matter)

Thanks in advance,
Julien

**Comment by ebecht** [comment]
Hi @Exenter 

Thank you for taking the time to read through the other issues.
While answering your query I realized that the package's code actually did not reflect the answer I gave in the issues you referenced. I just modified the code so that scores for your custom populations are actually computed and output.

Could you install the latest version from github and try again? Please let me know if you encounter any further problem.

I also fixed the HTTPS problem.

Thanks!
Etienne

**Comment by Exenter** [comment]
Hi,
Thanks ! Everything works like a charm now
