### ISSUE TITLE
substitute missing genes in Signatures/genes.txt

### ISSUE THREAD

**Issue by jazberna1** [ebecht/MCPcounter#24]
Dear MCPcounter developers,

This is not an issue, quite the opposite, I would like to run MCPcounter but I lack some of the genes in:
https://github.com/ebecht/MCPcounter/blob/master/Signatures/genes.txt

I was wondering whether it is possible to edit that file and substitute there the genes I am missing with others for which I have data and I assume behave as 'proxies' for the missing ones.

Many thanks
Jorge

**Comment by ebecht** [comment]
Hi Jorge,

Are you missing a lot of these genes? Since `MCP-counter` computes cellular scores by averaging the corresponding transcriptomic markers, it is usually ok to be missing some of the genes (since they are largely redundant).

If you want to edit / add the signatures you can download locally the file you linked and edit it, or edit it from within R. The argument that you eventually pass to `MCPcounter.estimate` is a `data.frame` corresponding to the content of that file.

It is fine if you edit the signatures but if you publish with it please make sure that you make it clear you did so!

Best,
Etienne

**Comment by jazberna1** [comment]
Hello Etienne,

Thanks so much for the quick reply.

I am afraid I am missing 75 genes from the Signatures/genes.txt file. I have attached here the list:
[missing_genes.txt](https://github.com/ebecht/MCPcounter/files/7235730/missing_genes.txt)

Am I right saying I am exeeding the acceptable number of missing genes? In such case I would edit Signatures/genes.txt and make sure I clarify so for publication.

Regards
Jorge

**Comment by ebecht** [comment]
That's quite a lot indeed, it is more than half of the total. You can check for each cell type how many markers are left, I'd say (arbitrarily) that if you have ~5 genes left per cell type it isn't so bad. Some cell types have less markers than this in the signature table file (e.g. CD8 T cells and dendritic cells I believe).

In any case, feel free to edit the signatures to your convenience, especially if you have data to back it up and are explicit about it!

Best,
Etienne

**Comment by jazberna1** [comment]
Hello Etienne,

Thanks so much for your help. I'll make sure any modification of the signatures is made explicit.

I'm closing this one

Thanks!
Jorge
