### ISSUE TITLE
Data normalization

### ISSUE THREAD

**Issue by Fclef** [ebecht/MCPcounter#28]
Hi

I have some TCGA logfpkm data which is min-max scaled between 0 to 1. Is MCP counter still suitable in this case? I got some pretty weird results which all samples cross cancer type show high score in fibroblasts, low for the rest. I'm wondering if min-max scaled data defeat the purpose of comparing cell type enrichment cross sample. Thanks!

**Comment by ebecht** [comment]
Hi,

Sorry for the late reply. Yes I think MCPcounter should still be applicable if your data has been re-scaled.

You should not compare scores from one cell type to score from another cell type. Results should be compared across samples for the same cell type.

This is because MCPcounter scores are averages of marker genes, and marker genes can have different expression levels.

Etienne
