### ISSUE TITLE
cannot install ebecht/MCPcounter

### ISSUE THREAD

**Issue by wangt-biotime** [ebecht/MCPcounter#7]
Hello, 
I'm trying to install MCPcounter, but I got this error.

> library(devtools)
> install_github("ebecht/MCPcounter",ref="master", subdir="Source")
Downloading GitHub repo ebecht/MCPcounter@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ebecht/MCPcounter/tarball/master'

What can I do to solve this problem? 
Thankyou

WT

**Comment by ebecht** [comment]
Hello @wangt-biotime 

I am not too sure what is causing the issue.

What you could do instead is the following:

1. Download [https://api.github.com/repos/ebecht/MCPcounter/tarball/master](https://api.github.com/repos/ebecht/MCPcounter/tarball/master) using your webbrowser
2. Start R and install `curl` if it is not already installed: `install.packages("curl")`
3. Install the package from source by running
   `install.packages("path/to/downloaded_file.tar.gz",type="source",repos=NULL)`

**Comment by jianguozhouzunyimedicaluniversity** [comment]
hello, @ebecht 
I used your method: in 22 jan.
but it's doesn't work.
1.install_github("ebecht/MCPcounter",ref="master", subdir="Source")
Skipping install of 'MCPcounter' from a github remote, the SHA1 (8c37884e) has not changed since last install.
  Use `force = TRUE` to force installation
2.install.packages("C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from 'C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz’ had non-zero exit status

**Comment by itamuria** [comment]
I have the same problem. 
Did you find any solution?
Thanks, 
Ibon

**Comment by shelber** [comment]
I have the same problem.

**Comment by ebecht** [comment]
@shelber Can you open your own issue and describe the problem in details please (commands ran, error messages, ...) ?
